import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'dlcf',
  description: 'Generated by HERVTECH',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="shortcut icon" type="image/jpg" href="/images/logo.jpg"/>
      <body>{children}</body>
    </html>
  )
}
// className={`${inter.className} `}